"""Release workflow models -- represents the full .github/workflows/release.yml."""

from __future__ import annotations

from typing import Annotated, Any

from pydantic import (
    AfterValidator,
    BaseModel,
    ConfigDict,
    Field,
    model_serializer,
    model_validator,
)


class WorkflowInput(BaseModel):
    """A single input for workflow_dispatch."""

    description: str = ""
    type: str = "string"
    required: bool = False


class WorkflowDispatch(BaseModel):
    """The workflow_dispatch trigger."""

    inputs: dict[str, WorkflowInput] = Field(
        default_factory=lambda: {
            "plan": WorkflowInput(
                description="Release plan JSON (generated by uvr release).",
                type="string",
                required=True,
            ),
        }
    )


class WorkflowTrigger(BaseModel):
    """The ``on:`` block. Editable -- users can add triggers."""

    model_config = ConfigDict(extra="allow")

    workflow_dispatch: WorkflowDispatch = Field(default_factory=WorkflowDispatch)


class Job(BaseModel):
    """Base for all jobs. Common overridable fields."""

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    runs_on: str = Field(default="ubuntu-latest", alias="runs-on")
    if_condition: str | None = Field(default=None, alias="if")
    needs: list[str] = Field(default_factory=list)
    environment: str | None = None
    concurrency: str | dict | None = None
    timeout_minutes: int | None = Field(default=None, alias="timeout-minutes")
    env: dict[str, str] | None = None
    strategy: dict = Field(default_factory=dict)
    steps: list[dict] = Field(default_factory=list)

    @model_serializer(mode="wrap")
    def _drop_empty(self, handler: Any) -> dict:
        d = handler(self)
        if "needs" in d and d["needs"] == []:
            del d["needs"]
        if "strategy" in d and d["strategy"] == {}:
            del d["strategy"]
        return d


# Shorthand for plan access in GitHub Actions expressions
_P = "fromJSON(inputs.plan)"

_CHECKOUT = {
    "id": "checkout",
    "uses": "actions/checkout@v4",
    "with": {"fetch-depth": 0},
}
_SETUP_UV = {"id": "setup-uv", "uses": "astral-sh/setup-uv@v5"}
_SETUP_PY = {
    "id": "setup-python",
    "name": "Set up Python",
    "run": (
        f"uv python install ${{{{ {_P}.python_version }}}}\n"
        f"uv tool install ${{{{ {_P}.uvr_install }}}}"
    ),
}


def _needs_validator(*required: str):
    """Create a model_validator that ensures needs contains the required jobs."""

    @model_validator(mode="after")
    def _check(self: Job) -> Job:
        for dep in required:
            if dep not in self.needs:
                self.needs.insert(0, dep)
        return self

    return _check


def _warn_if_changed(default: Any, msg: str) -> AfterValidator:
    """AfterValidator that warns when a value differs from *default*."""
    import warnings

    def _check(v: Any) -> Any:
        if v != default:
            warnings.warn(msg, UserWarning, stacklevel=2)
        return v

    return AfterValidator(_check)


def WarnIfChanged(tp: Any, expected: Any, *, msg: str = "", **field_kwargs: Any) -> Any:  # noqa: N802
    """Return an ``Annotated`` type that warns when a field is modified.

    Bundles the type, ``Field(...)`` and an ``AfterValidator`` into one
    annotation so that frozen job fields collapse to a single declaration.

    *expected* is the value checked by the validator. Pass ``default`` or
    ``default_factory`` in **field_kwargs** to control how pydantic
    initialises the field — just like ``Field()``.
    """
    validator = _warn_if_changed(
        expected, msg or "frozen field was modified from its default"
    )
    return Annotated[tp, Field(**field_kwargs), validator]


_VALIDATE_PLAN_STEPS: list[dict] = [
    _SETUP_UV,
    _SETUP_PY,
    {
        "id": "validate-plan",
        "name": "Validate release plan",
        "env": {"UVR_PLAN": "${{ inputs.plan }}"},
        "run": "uvr validate-plan",
    },
]


class ValidatePlanJob(Job):
    """The validate-plan job. Frozen -- runs first to validate plan JSON."""

    steps: WarnIfChanged(  # ty: ignore[invalid-type-form]
        list[dict],
        _VALIDATE_PLAN_STEPS,
        default_factory=lambda: list(_VALIDATE_PLAN_STEPS),
        msg="validate-plan.steps was modified",
    )


_BUILD_IF = f"${{{{ !contains({_P}.skip, 'build') }}}}"
_BUILD_RUNS_ON = "${{ matrix.runner }}"
_BUILD_STRATEGY: dict = {
    "fail-fast": True,
    "matrix": {"runner": f"${{{{ {_P}.build_matrix }}}}"},
}
_BUILD_STEPS: list[dict] = [
    _CHECKOUT,
    _SETUP_UV,
    _SETUP_PY,
    {
        "id": "build",
        "name": "Build packages",
        "env": {
            "GH_TOKEN": "${{ github.token }}",
            "UVR_PLAN": "${{ inputs.plan }}",
        },
        "run": "uvr build --runner '${{ toJSON(matrix.runner) }}'",
    },
    {
        "id": "upload",
        "uses": "actions/upload-artifact@v4",
        "with": {
            "name": "wheels-${{ join(matrix.runner, '-') }}",
            "path": "dist/*.whl",
            "if-no-files-found": "error",
        },
    },
]


class BuildJob(Job):
    """The build job. Frozen -- immutable fields enforced per-field."""

    if_condition: WarnIfChanged(  # ty: ignore[invalid-type-form]
        str | None,
        _BUILD_IF,
        default=_BUILD_IF,
        msg="build.if was modified",
        alias="if",
    )
    strategy: WarnIfChanged(  # ty: ignore[invalid-type-form]
        dict,
        _BUILD_STRATEGY,
        default_factory=lambda: dict(_BUILD_STRATEGY),
        msg="build.strategy was modified",
    )
    runs_on: WarnIfChanged(  # ty: ignore[invalid-type-form]
        str,
        _BUILD_RUNS_ON,
        default=_BUILD_RUNS_ON,
        msg="build.runs-on was modified",
        alias="runs-on",
    )
    steps: WarnIfChanged(  # ty: ignore[invalid-type-form]
        list[dict],
        _BUILD_STEPS,
        default_factory=lambda: list(_BUILD_STEPS),
        msg="build.steps was modified",
    )
    _ensure_needs = _needs_validator("validate_plan")


_RELEASE_IF = f"${{{{ always() && !failure() && !contains({_P}.skip, 'release') }}}}"
_RELEASE_STRATEGY: dict = {
    "fail-fast": False,
    "matrix": {"include": f"${{{{ {_P}.release_matrix }}}}"},
}
_RELEASE_STEPS: list[dict] = [
    {
        "id": "download",
        "uses": "actions/download-artifact@v4",
        "with": {
            "pattern": "wheels-*",
            "merge-multiple": True,
            "path": "dist",
            "run-id": f"${{{{ {_P}.reuse_run_id != '' && {_P}.reuse_run_id || github.run_id }}}}",
        },
    },
    {
        "id": "publish",
        "uses": "softprops/action-gh-release@v2",
        "with": {
            "tag_name": "${{ matrix.tag }}",
            "name": "${{ matrix.title }}",
            "body": "${{ matrix.body }}",
            "files": "dist/${{ matrix.dist_name }}-${{ matrix.version }}*.whl",
            "make_latest": "${{ matrix.make_latest }}",
        },
    },
]


class ReleaseJob(Job):
    """The release job. Frozen -- immutable fields enforced per-field."""

    if_condition: WarnIfChanged(  # ty: ignore[invalid-type-form]
        str | None,
        _RELEASE_IF,
        default=_RELEASE_IF,
        msg="release.if was modified",
        alias="if",
    )
    strategy: WarnIfChanged(  # ty: ignore[invalid-type-form]
        dict,
        _RELEASE_STRATEGY,
        default_factory=lambda: dict(_RELEASE_STRATEGY),
        msg="release.strategy was modified",
    )
    steps: WarnIfChanged(  # ty: ignore[invalid-type-form]
        list[dict],
        _RELEASE_STEPS,
        default_factory=lambda: list(_RELEASE_STEPS),
        msg="release.steps was modified",
    )
    _ensure_needs = _needs_validator("build")


_FINALIZE_IF = f"${{{{ always() && !failure() && !contains({_P}.skip, 'finalize') }}}}"
_FINALIZE_STEPS: list[dict] = [
    _CHECKOUT,
    _SETUP_UV,
    _SETUP_PY,
    {
        "id": "finalize",
        "name": "Finalize release",
        "env": {"UVR_PLAN": "${{ inputs.plan }}"},
        "run": "uvr finalize",
    },
]


class FinalizeJob(Job):
    """The finalize job. Frozen -- immutable fields enforced per-field."""

    if_condition: WarnIfChanged(  # ty: ignore[invalid-type-form]
        str | None,
        _FINALIZE_IF,
        default=_FINALIZE_IF,
        msg="finalize.if was modified",
        alias="if",
    )
    steps: WarnIfChanged(  # ty: ignore[invalid-type-form]
        list[dict],
        _FINALIZE_STEPS,
        default_factory=lambda: list(_FINALIZE_STEPS),
        msg="finalize.steps was modified",
    )
    _ensure_needs = _needs_validator("release")


class WorkflowJobs(BaseModel):
    """All jobs in the release workflow."""

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    validate_plan: ValidatePlanJob = Field(default_factory=ValidatePlanJob)
    build: BuildJob = Field(default_factory=BuildJob)
    release: ReleaseJob = Field(default_factory=ReleaseJob)
    finalize: FinalizeJob = Field(default_factory=FinalizeJob)


class ReleaseWorkflow(BaseModel):
    """Full representation of .github/workflows/release.yml.

    The YAML file is the source of truth. This model validates its
    structure after edits made via ``uvr workflow``. The Jinja2 template
    generates the initial YAML; this model ensures user edits don't
    break it.
    """

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    name: str = "Release Wheels"
    on: WorkflowTrigger = Field(default_factory=WorkflowTrigger)
    permissions: dict[str, str] = Field(default_factory=lambda: {"contents": "write"})
    jobs: WorkflowJobs = Field(default_factory=WorkflowJobs)

    @model_validator(mode="before")
    @classmethod
    def _normalize_on_key(cls, data: Any) -> Any:
        """PyYAML parses ``on:`` as boolean ``True`` -- normalize to string."""
        if isinstance(data, dict) and True in data:
            data["on"] = data.pop(True)
        return data


JOB_ORDER: list[str] = [
    "validate_plan",
    "build",
    "release",
    "finalize",
]
"""Canonical ordering of jobs in the release workflow pipeline."""
