"""Execution: run pre-computed commands from a ReleasePlan."""

from __future__ import annotations

import subprocess
import sys

from .models import PlanCommand, ReleasePlan


class ReleaseExecutor:
    """Runs pre-computed commands from a ReleasePlan.

    The executor contains NO domain logic — it just calls subprocess.run()
    on the command lists generated by the planner.
    """

    def __init__(self, plan: ReleasePlan) -> None:
        self.plan = plan

    def build(self, *, runner: str | None = None) -> None:
        """Run build commands."""
        if runner:
            self._run_commands(self.plan.build_commands.get(runner, []))
        else:
            for r in self.plan.runners:
                self._run_commands(self.plan.build_commands.get(r, []))

    def publish(self) -> None:
        """Run publish commands."""
        self._run_commands(self.plan.publish_commands)

    def finalize(self) -> None:
        """Run finalize commands."""
        self._run_commands(self.plan.finalize_commands)

    def run(self) -> None:
        """Execute all phases: build → publish → finalize."""
        self.build()
        self.publish()
        self.finalize()

    @staticmethod
    def _run_commands(commands: list[PlanCommand]) -> None:
        for cmd in commands:
            if cmd.label:
                print(f"  {cmd.label}")
            result = subprocess.run(cmd.args)
            if cmd.check and result.returncode != 0:
                print(
                    f"Command failed: {' '.join(cmd.args)}",
                    file=sys.stderr,
                )
                sys.exit(1)
